<?php

declare(strict_types=1);

require __DIR__ . '/bootstrap.php';

use Mnb\PHPExcel\MnbExcel;

$rows = [
    ['name' => 'Ravi Kumar', 'email' => 'ravi@example.com', 'marks' => 95, 'status' => 'pass', 'amount' => 1250.50],
    ['name' => 'Sita Devi', 'email' => 'sita@example.com', 'marks' => 58, 'status' => 'review', 'amount' => 980.00],
    ['name' => 'Arun', 'email' => 'arun@example.com', 'marks' => 42, 'status' => 'fail', 'amount' => 760.25],
];

$builder = MnbExcel::report($rows, 'business')
    ->title('Student Export')
    ->columns([
        'name' => 'Student Name',
        'email' => 'Email Address',
        'marks' => 'Marks',
        'status' => 'Status',
        'amount' => 'Amount',
    ])
    ->metadata(['title' => 'Student Export', 'creator' => 'MNB Tests', 'company' => 'MNB'])
    ->autoWidth(['min' => 9, 'max' => 30, 'padding' => 2])
    ->integerColumns(['marks'])
    ->currencyColumns(['amount'], '$')
    ->conditionalRowStyle(static fn (array $row): bool => ($row['status'] ?? '') === 'fail', 'mnb.row.danger')
    ->conditionalRowStyle(static fn (array $row): bool => ($row['status'] ?? '') === 'review', 'mnb.row.warning')
    ->footerRows('Generated by MNB PHPExcel');

$workbook = $builder->toWorkbookData();
$sheet = $workbook->sheets[0];

assert($workbook->metadata['title'] === 'Student Export');
assert($workbook->metadata['creator'] === 'MNB Tests');
assert(isset($sheet->columnWidths[1], $sheet->columnWidths[2]));
assert($sheet->columnWidths[2] >= 13);

// Report title row = 1, header row = 2, data rows = 3,4,5.
assert($sheet->rowStyles[4] === 'mnb.row.warning');
assert($sheet->rowStyles[5] === 'mnb.row.danger');

assert(MnbExcel::safeFileName('Student Export Report 2026.xlsx') === 'Student_Export_Report_2026.xlsx');
assert(MnbExcel::safeFileName('../bad:name?.xlsx', 'xlsx') === 'bad_name.xlsx');

$summary = MnbExcel::fromImportSummary([
    'status' => 'warning',
    'total_rows' => 3,
    'missing_required_columns' => ['phone'],
], [
    'valid' => [$rows[0]],
    'failed' => [['row' => 3, 'errors' => ['Invalid email'], 'data' => $rows[1]]],
])->toArray();

assert($summary[0] === ['Metric', 'Value']);
assert($summary[1] === ['status', 'warning']);
assert($summary[2] === ['total_rows', 3]);
assert($summary[3] === ['missing_required_columns', 'phone']);

$withSummary = MnbExcel::fromFailedRows([
    ['row' => 3, 'errors' => ['Invalid email'], 'data' => ['name' => 'Sita']],
])->withImportSummarySheet(['total_rows' => 2])->toWorkbookData();

assert(count($withSummary->sheets) === 2);
assert($withSummary->sheets[1]->name === 'Import Summary');

echo "Export polish smoke test passed.\n";
