<?php

declare(strict_types=1);

require __DIR__ . '/bootstrap.php';

use Mnb\PHPExcel\MnbExcel;

$rows = [
    ['month' => 'January', 'revenue' => 12500.50, 'margin' => 0.32],
    ['month' => 'February', 'revenue' => 18300.75, 'margin' => 0.36],
];

$array = MnbExcel::report($rows, 'finance')
    ->title('Revenue Report')
    ->titleRow('Generated for internal review')
    ->columns([
        'month' => 'Month',
        'revenue' => 'Revenue',
        'margin' => 'Margin',
    ])
    ->currencyColumns(['revenue'], '$')
    ->percentageColumns(['margin'])
    ->summaryRows([
        ['Total', 30801.25, 0.34],
    ])
    ->footerRows('Generated by MNB PHPExcel')
    ->toArray();

assert($array[0][0] === 'Revenue Report');
assert($array[2] === ['Month', 'Revenue', 'Margin']);
assert($array[3][0] === 'January');
assert($array[5][0] === 'Total');
assert($array[6][0] === 'Generated by MNB PHPExcel');

echo "Report builder smoke test passed.\n";
