<?php

declare(strict_types=1);

require __DIR__ . '/../tests/bootstrap.php';

use Mnb\PHPExcel\MnbExcel;

$rows = [
    ['student' => 'Ravi Kumar', 'email' => 'ravi@example.com', 'marks' => 95, 'status' => 'pass', 'amount' => 1250.50, 'created_at' => '2026-07-01 10:00:00'],
    ['student' => 'Sita Devi', 'email' => 'sita@example.com', 'marks' => 58, 'status' => 'review', 'amount' => 980.00, 'created_at' => '2026-07-01 10:10:00'],
    ['student' => 'Arun', 'email' => 'arun@example.com', 'marks' => 42, 'status' => 'fail', 'amount' => 760.25, 'created_at' => '2026-07-01 10:20:00'],
];

$output = MnbExcel::report($rows, 'business')
    ->title('Student Export Polish Report')
    ->columns([
        'student' => 'Student Name',
        'email' => 'Email Address',
        'marks' => 'Marks',
        'status' => 'Status',
        'amount' => 'Fee Amount',
        'created_at' => 'Created At',
    ])
    ->metadata([
        'title' => 'Student Export Polish Report',
        'subject' => 'Demo report generated by MNB PHPExcel v0.6.0',
        'creator' => 'MNB PHPExcel',
        'company' => 'MNB',
        'keywords' => 'excel,array,php,export',
    ])
    ->autoWidth(['min' => 10, 'max' => 38, 'padding' => 3])
    ->integerColumns(['marks'])
    ->currencyColumns(['amount'], '₹')
    ->datetimeStyleColumns(['created_at'])
    ->conditionalRowStyle(
        static fn (array $row): bool => ($row['status'] ?? '') === 'fail',
        'mnb.row.danger'
    )
    ->conditionalRowStyle(
        static fn (array $row): bool => ($row['status'] ?? '') === 'review',
        'mnb.row.warning'
    )
    ->summaryRows([
        ['Average marks', 65, '', '', '', ''],
    ])
    ->footerRows('Generated by MNB PHPExcel v0.6.0')
    ->freezeHeader()
    ->autoFilter()
    ->saveSafe(__DIR__ . '/../storage/examples', 'Student Export Polish Report', 'xlsx');

echo "Exported: {$output}\n";
