<?php

declare(strict_types=1);

require __DIR__ . '/../vendor/autoload.php';

use Mnb\PHPExcel\MnbExcel;

$rows = [
    ['month' => 'January', 'revenue' => 12500.50, 'expenses' => 8200.25, 'margin' => 0.344],
    ['month' => 'February', 'revenue' => 18300.75, 'expenses' => 11100.50, 'margin' => 0.393],
    ['month' => 'March', 'revenue' => 22000.00, 'expenses' => 14300.00, 'margin' => 0.350],
];

MnbExcel::report($rows, 'finance')
    ->title('Quarterly Revenue Report')
    ->titleRow('Generated by MNB PHPExcel report builder', [
        'merge' => true,
        'style' => 'mnb.subtitle',
    ])
    ->columns([
        'month' => 'Month',
        'revenue' => 'Revenue',
        'expenses' => 'Expenses',
        'margin' => 'Margin',
    ])
    ->columnWidths([
        'A' => 18,
        'B' => 16,
        'C' => 16,
        'D' => 14,
    ])
    ->currencyColumns(['revenue', 'expenses'], '$')
    ->percentageColumns(['margin'])
    ->summaryRows([
        ['Total', 52801.25, 33600.75, 0.362],
    ])
    ->footerRows('Confidential — generated for internal review')
    ->save(__DIR__ . '/output/revenue-report.xlsx');

echo "Created examples/output/revenue-report.xlsx\n";
