<?php

declare(strict_types=1);

return [
    'core' => [
        'name' => 'mnb/mnb-phpexcel-core',
        'description' => 'Shared data model, typed reader API, sessions, projection, progress, errors, and reader registry for MNB PHPExcel.',
        'require' => ['php' => '>=8.1', 'ext-json' => '*'],
        'files' => [
            'src/Application/LoggerBridge.php',
            'src/Application/RowTransformerPipeline.php',
            'src/Contracts/ReaderPluginInterface.php',
            'src/Contracts/WriterPluginInterface.php',
            'src/Core/CellValue.php',
            'src/Core/RichText.php',
            'src/Core/RichTextRun.php',
            'src/Core/WorkbookData.php',
            'src/Core/WorkbookFactory.php',
            'src/Core/WorksheetData.php',
            'src/Events/*.php',
            'src/Reader/ColumnProjection.php',
            'src/Reader/HeaderDetector.php',
            'src/Reader/IterableReaderInterface.php',
            'src/Reader/Options/*.php',
            'src/Reader/Plugin/*.php',
            'src/Reader/ReaderInterface.php',
            'src/Reader/ReaderRegistry.php',
            'src/Reader/ReadSession.php',
            'src/Reader/State/*.php',
            'src/SpreadsheetManager.php',
            'src/Support/Arr.php',
            'src/Support/AtomicFileWriter.php',
            'src/Support/Coordinate.php',
            'src/Support/ErrorCode.php',
            'src/Support/ErrorReporter.php',
            'src/Support/FileFormatDetector.php',
            'src/Support/LocaleNormalizer.php',
            'src/Support/MnbExcelException.php',
            'src/Support/Zip/*.php',
            'src/Support/Xml/*.php',
            'src/Support/SheetNameAllocator.php',
            'src/Support/ValueSanitizer.php',
            'src/Validation/*.php',
        ],
    ],
    'csv' => [
        'name' => 'mnb/mnb-phpexcel-csv',
        'description' => 'CSV reader/writer module for MNB PHPExcel.',
        'require' => ['php' => '>=8.1', 'mnb/mnb-phpexcel-core' => '^1.4'],
        'files' => [
            'src/Format/Csv.php',
            'src/Reader/CsvReader.php',
            'src/Support/CsvDialect.php',
            'src/Support/EncodingDetector.php',
            'src/Writer/CsvWriter.php',
        ],
    ],
    'json' => [
        'name' => 'mnb/mnb-phpexcel-json',
        'description' => 'Streaming JSON and NDJSON reader/writer module for MNB PHPExcel.',
        'require' => ['php' => '>=8.1', 'ext-json' => '*', 'mnb/mnb-phpexcel-core' => '^1.4'],
        'files' => [
            'src/Format/Json.php',
            'src/Reader/JsonReader.php',
            'src/Reader/StreamingJsonArrayParser.php',
            'src/Support/JsonArrayNormalizer.php',
            'src/Writer/JsonWriter.php',
        ],
    ],
    'xml' => [
        'name' => 'mnb/mnb-phpexcel-xml',
        'description' => 'Streaming XML reader, schema mapping, and XML writer module for MNB PHPExcel.',
        'require' => ['php' => '>=8.1', 'mnb/mnb-phpexcel-core' => '^1.6'],
        'suggest' => ['ext-xmlreader' => 'Recommended for true streaming XML reads; a pure-PHP fallback is included.'],
        'files' => [
            'src/Format/Xml.php',
            'src/Reader/XmlReader.php',
            'src/Reader/XmlSchemaMapping.php',
            'src/Writer/XmlWriter.php',
        ],
    ],
    'xlsx' => [
        'name' => 'mnb/mnb-phpexcel-xlsx',
        'description' => 'Native XLSX reader/writer with password encryption, document protection, formulas, pivots, and low-memory streaming for MNB PHPExcel.',
        'require' => [
            'php' => '>=8.1',
            'ext-iconv' => '*',
            'ext-openssl' => '*',
            'mnb/mnb-phpexcel-core' => '^1.7',
        ],
        'suggest' => [
            'ext-zip' => 'Recommended for native high-performance XLSX package access; a pure-PHP fallback is included.',
            'ext-xmlreader' => 'Recommended for true streaming XLSX reads; a pure-PHP fallback is included.',
            'phpoffice/phpspreadsheet' => 'Adds compatibility for specialist formulas outside the expanded native formula engine.',
        ],
        'files' => [
            'src/Application/UploadSafetyValidator.php',
            'src/Format/Xlsx.php',
            'src/Large/ImportMethodAdvisor.php',
            'src/Large/LargeExcelPreflightAnalyzer.php',
            'src/Large/LargeSharedStringCache.php',
            'src/Large/LargeXlsxReadSession.php',
            'src/Large/LargeXlsxStreamingReader.php',
            'src/Large/LargeXlsxStreamingWriter.php',
            'src/Large/LargeXlsxWriteSession.php',
            'src/Reader/MergedCellMap.php',
            'src/Reader/Formula/*.php',
            'src/Reader/SharedStrings/*.php',
            'src/Reader/XlsxImageExtractor.php',
            'src/Reader/XlsxInspector.php',
            'src/Reader/XlsxQuickInfo.php',
            'src/Reader/XlsxMetadataExtractor.php',
            'src/Reader/XlsxProtectionReader.php',
            'src/Reader/XlsxReader.php',
            'src/Reader/XlsxStyleMap.php',
            'src/Reader/XlsxWorkbookResolver.php',
            'src/Security/*.php',
            'src/Support/AdvancedWorkbookCapabilities.php',
            'src/Support/CompatibilityFixtureSuite.php',
            'src/Support/XlsxCompatibilityVerifier.php',
            'src/Support/XlsxIntegrityValidator.php',
            'src/Writer/XlsxWriter.php',
        ],
    ],
    'ods' => [
        'name' => 'mnb/mnb-phpexcel-ods',
        'description' => 'Native streaming ODS reader module for MNB PHPExcel.',
        'require' => ['php' => '>=8.1', 'mnb/mnb-phpexcel-core' => '^1.6'],
        'suggest' => [
            'ext-zip' => 'Recommended for native ODS package access; a pure-PHP fallback is included.',
            'ext-xmlreader' => 'Recommended for true streaming ODS reads; a pure-PHP fallback is included.',
        ],
        'files' => ['src/Format/Ods.php', 'src/Reader/OdsReader.php'],
    ],
    'xls' => [
        'name' => 'mnb/mnb-phpexcel-xls',
        'description' => 'Legacy XLS reader and writer support for MNB PHPExcel, backed by PhpSpreadsheet.',
        'require' => [
            'php' => '>=8.1',
            'mnb/mnb-phpexcel-core' => '^1.6',
            'phpoffice/phpspreadsheet' => '^2.1 || ^3.3 || ^4.0 || ^5.0',
        ],
        'files' => ['src/Compatibility/XlsReader.php', 'src/Compatibility/XlsWriter.php', 'src/Format/Xls.php'],
    ],
    'database' => [
        'name' => 'mnb/mnb-phpexcel-database',
        'description' => 'PDO imports, typed domain presets, validation, resumable manifests, and failed-row reporting for MNB PHPExcel.',
        'require' => ['php' => '>=8.1', 'ext-pdo' => '*', 'mnb/mnb-phpexcel-core' => '^1.4', 'mnb/mnb-phpexcel-xlsx' => '^1.4'],
        'files' => [
            'src/Contracts/DatabaseTargetInterface.php',
            'src/Domain/*.php',
            'src/Import/*.php',
            'src/Large/LargeExcelDatabaseImportEngine.php',
            'src/Large/LargeFailedRowsCsvWriter.php',
            'src/Large/LargeImportManifest.php',
            'src/Large/LargePdoCursor.php',
            'src/Support/DatabaseConfigResolver.php',
            'src/Support/DatabaseConnectionFactory.php',
            'src/Support/DatabaseIntegrationSuite.php',
        ],
    ],
    'application' => [
        'name' => 'mnb/mnb-phpexcel-application',
        'description' => 'Legacy facade, workbook builder, application helpers, plugins, diagnostics, and full workflow API for MNB PHPExcel.',
        'require' => [
            'php' => '>=8.1',
            'mnb/mnb-phpexcel-core' => '^1.7',
            'mnb/mnb-phpexcel-csv' => '^1.4',
            'mnb/mnb-phpexcel-json' => '^1.4',
            'mnb/mnb-phpexcel-xml' => '^1.6',
            'mnb/mnb-phpexcel-xlsx' => '^1.7',
            'mnb/mnb-phpexcel-ods' => '^1.6',
            'mnb/mnb-phpexcel-xls' => '^1.6',
            'mnb/mnb-phpexcel-database' => '^1.4',
        ],
        'files' => [
            'src/Application/ImportDashboardHelper.php',
            'src/Application/ImportJobRunner.php',
            'src/Application/ImportProfile.php',
            'src/Application/ImportProfileManager.php',
            'src/Application/ImportStatusReader.php',
            'src/Application/AjaxUploadHandler.php',
            'src/Application/MultiFileImportManager.php',
            'src/Application/AjaxUploader.php',
            'src/Application/Http/*.php',
            'src/Application/SpreadsheetApi.php',
            'src/Application/Mail/*.php',
            'src/Application/Queue/*.php',
            'src/Application/Schedule/*.php',
            'src/Core/WorkbookBuilder.php',
            'src/MnbExcel.php',
            'src/Plugin/*.php',
            'src/Storage/*.php',
            'src/Support/BenchmarkSuite.php',
            'src/Support/EnvironmentDiagnostics.php',
            'src/Support/ReleaseReadiness.php',
        ],
    ],
    'all' => [
        'name' => 'mnb/mnb-phpexcel-all',
        'description' => 'Metapackage installing every MNB PHPExcel module.',
        'type' => 'metapackage',
        'require' => ['php' => '>=8.1', 'mnb/mnb-phpexcel-application' => '^1.7'],
        'files' => [],
    ],
];
